### ISSUE TITLE
Feat: Search functionality

### ISSUE THREAD

**Issue by Sanchitbajaj02** [programerr01/Leaderboard#2]
Your project is amazing but I feel like a simple search box would be great. I can try to add a simple search box if you want😊.

**Comment by programerr01** [comment]
sure, that would be great @Sanchitbajaj02

**Comment by programerr01** [comment]
hii @Sanchitbajaj02 , is it possible to get rank too with the search result ? 
![image](https://github.com/programerr01/Leaderboard/assets/61112300/dab0b289-2ede-485b-9207-6211e083f2a7)

**Comment by Sanchitbajaj02** [comment]
> hii @Sanchitbajaj02 , is it possible to get rank too with the search result ? ![image](https://user-images.githubusercontent.com/61112300/244340676-dab0b289-2ede-485b-9207-6211e083f2a7.png)

I can try to make it happen. Currently, the rank does not come from the API but generates according to the indexing of data. I will research and make the PR if I find any solution

**Comment by programerr01** [comment]
sorted data is stored in `GLOBAL_DT` variable , you can simply search through it and access the index
