### ISSUE TITLE
Making Load More Button in Center 

### ISSUE THREAD

**Issue by PatilHarshh** [programerr01/Leaderboard#6]
if we make Load more Button in center and make it beautiful i will looks great @programerr01 
![Screenshot (86)](https://github.com/programerr01/Leaderboard/assets/120102234/5cc4021e-ec0e-46ea-87c5-8afaf778369d)

**Comment by singodiyashubham87** [comment]
@programerr01 I can do this, assign me the issue.

**Comment by programerr01** [comment]
@MisterMickey  @PatilHarshh One of you  , check #8

**Comment by PatilHarshh** [comment]
done #8
