### ISSUE TITLE
Make changes to UI to look more better.

### ISSUE THREAD

**Issue by singodiyashubham87** [programerr01/Leaderboard#7]
I want to make changes to UI and add some hover effects on buttons to make the UX more better.

**Comment by programerr01** [comment]
go for it

**Comment by programerr01** [comment]
@MisterMickey  , since the stylesheet has grown to it's limit. It would be better to add new `styles.css` file and attach with html file

**Comment by singodiyashubham87** [comment]
@programerr01 How's this?

**Changes Made:**
Theme change, font change, Hover effect added on buttons and drop shadow in input.

Any other changes you wanna suggest?

![Screenshot from 2023-06-17 12-30-30](https://github.com/programerr01/Leaderboard/assets/93720428/eef4a8e6-6452-4ccb-a2be-d65b3af0f9ce)

**Comment by programerr01** [comment]
great work @MisterMickey

**Comment by programerr01** [comment]
Search button and clear filter button can be made more compact , right now it's very stretched

**Comment by singodiyashubham87** [comment]
@programerr01 Here we go, anything else?

![Screenshot from 2023-06-17 12-43-06](https://github.com/programerr01/Leaderboard/assets/93720428/4008ef72-3843-4f17-95ef-edd629746eef)

**Comment by programerr01** [comment]
great, looks better now.
