### ISSUE TITLE
Dynamic Search (Matching parts of username)

### ISSUE THREAD

**Issue by programerr01** [programerr01/Leaderboard#8]
## Issue 
Right now, if you search for username , you have to enter complete username then only result will be shown. 
It would be better  solution to match part of username for broader results. 

## Solution 
instead of using `==` while searching for username like `user == searched_user` , using `includes()` method of javascript will be better.
`includes` return the index of particular sub_string in the original string , if not present in string it will return -1

**Comment by PatilHarshh** [comment]
ok i want to proceed for this issue @programerr01

**Comment by PatilHarshh** [comment]
done #9 @programerr01 and dont forget to use label
